// Execute real app startup and navigation with deliberately unresolved server reads.
import assert from 'node:assert/strict';
const listeners={},app={innerHTML:''},label={textContent:''};
const button={disabled:false,textContent:''},form={querySelector:()=>button,setAttribute(){},removeAttribute(){}};
const theme={setAttribute(){},querySelector:()=>label};
let clock=100000;Date.now=()=>clock;
const nav=['stock','kitchen','employees','stores','suppliers'].map(view=>({dataset:{view}}));
const elements={'#app':app,'#login-form':form,'#login-error':{textContent:''},'#sidebar-toggle':{setAttribute(){}},'#active-store':{value:'A'},'#logout':{}};
globalThis.HTMLInputElement=class{get value(){return ''}set value(value){}};
globalThis.MutationObserver=class{observe(){}};
globalThis.document={documentElement:{dataset:{theme:'light'}},activeElement:null,addEventListener(){},querySelector:key=>elements[key]||null,querySelectorAll:key=>key==='[data-theme-toggle]'?[theme]:key==='[data-view]'?nav:[]};
globalThis.window={posConfigReady:Promise.resolve({configured:true,url:'https://fixture.test',key:'fixture'}),addEventListener(){}};
globalThis.localStorage={getItem(){return null},setItem(){}};
globalThis.setInterval=()=>0;
globalThis.FormData=class{*[Symbol.iterator](){yield ['identifier','fixture'];yield ['password','test']}};
let reads=[];
const profile={me:{id:'test',userId:'test',name:'Test',role:'owner'},stores:[{id:'A',name:'Outlet A'},{id:'B',name:'Outlet B'}],access:{sell:true,kitchen:true,stock:true,employees:true,master:true}};
globalThis.fetch=async(url,options)=>{
 if(url==='/api/pos-login')return new Response(JSON.stringify({access_token:'fixture',refresh_token:'fixture',expires_in:3600,user:{id:'test'}}));
 if(url.endsWith('/pos_bootstrap'))return new Response(JSON.stringify(profile));
 return new Promise(resolve=>reads.push({url,options,resolve}));
};
await import('../pos/app.js?navigation-regression');
await form.onsubmit({currentTarget:form,preventDefault(){}});
assert.match(app.innerHTML,/Selamat datang/);
assert.equal(reads.length,1,'one background prefetch');
nav[0].onclick();assert.match(app.innerHTML,/data-view="stock"[^>]+class="active"/);
assert(!app.innerHTML.includes('Membuka menu'));
nav[1].onclick();assert.match(app.innerHTML,/data-view="kitchen"[^>]+class="active"/);
await Promise.resolve();assert.equal(reads.length,2,'service read can run while full read pending');
elements['#active-store'].value='B';elements['#active-store'].onchange({target:elements['#active-store']});
await Promise.resolve();assert.equal(reads.length,3);
assert.equal(JSON.parse(reads[2].options.body).branch,'B');
elements['#logout'].onclick();assert.match(app.innerHTML,/login-form/);
for(const read of reads)read.resolve(new Response(JSON.stringify(profile)));
await new Promise(resolve=>setTimeout(resolve,0));
assert.match(app.innerHTML,/login-form/,'responses from previous account cannot reopen app');
reads=[];
await form.onsubmit({currentTarget:form,preventDefault(){}});
nav[3].onclick();assert.match(app.innerHTML,/data-view="stores"[^>]+class="active"/);
reads[0].resolve(new Response(JSON.stringify({...profile,opsVersion:9})));
await new Promise(resolve=>setTimeout(resolve,0));
assert.match(app.innerHTML,/Master Store/);
clock+=16000;
nav[4].onclick();assert.match(app.innerHTML,/Kelola supplier/,'cached page opens before request finishes');
await Promise.resolve();assert.equal(reads.length,2);
const editedPage=app.innerHTML;document.activeElement={matches:()=>true};
reads[1].resolve(new Response(JSON.stringify({...profile,opsVersion:9,stores:[{id:'A',name:'Updated Outlet A'},{id:'B',name:'Outlet B'}]})));
await new Promise(resolve=>setTimeout(resolve,0));
assert.equal(app.innerHTML,editedPage,'background update must preserve an active input');
document.activeElement=null;nav[3].onclick();assert.match(app.innerHTML,/Updated Outlet A/);
console.log('PASS real app: immediate navigation, outlet/logout race protection, cached pages, background prefetch and preservation of active form input');
