import assert from 'node:assert/strict';
import {emptyState,money} from '../pos/core.mjs';
import {inventoryPanel} from '../pos/inventory-ui.mjs';
import {deleteProduct,collapseSingleVariants} from '../pos/product-stock.mjs';
import {posMenuEntries} from '../pos/pos-menu.mjs';
import {Node} from './variant-dom.mjs';
const product=(id,name,extra={})=>({id,name,sku:id,itemType:'finished',stockUnit:'pcs',category:'Olahan Duren',salePrice:50000,buyPrice:30000,...extra});
const a=product('a','Durpas A',{variantGroupId:'group',variantGroupName:'Durpas',variant:'A',variantOptions:[{name:'Rasa',value:'A'}],photo:'data:image/png;base64,AAAA'});
const b=product('b','Durpas B',{variantGroupId:'group',variantGroupName:'Durpas',variant:'B',variantOptions:[{name:'Rasa',value:'B'}],salePrice:'135000',buyPrice:90000,photo:'data:image/png;base64,BBBB'});
const single=product('single','Pancake',{salePrice:25000,buyPrice:15000,photo:'data:image/png;base64,CCCC'});
const state={...emptyState(),products:[b,single,a],stores:[{id:'outlet',name:'Outlet'}]};
const before=structuredClone(state);
const render=(filter={})=>{const root=new Node();root.innerHTML=inventoryPanel(state,'outlet',filter,'products');return root;};
let root=render(),group=root.querySelector('.has-variants'),summary=group.querySelector('summary');
assert.equal(summary.querySelector('img').attrs.src,a.photo,'Thumbnail is the first displayed variant, not input array order');
assert.match(summary.textContent,/2 varian/);
assert.equal(summary.querySelector('[data-card-sale] strong').textContent,`${money(50000)} – ${money(135000)}`);
assert.equal(summary.querySelector('[data-card-buy] strong').textContent,`${money(30000)} – ${money(90000)}`);
const leaves=group.querySelectorAll('.inv-card');
assert.equal(leaves[0].querySelector('.inv-metric strong').textContent,money(50000));
assert.equal(leaves[1].querySelector('.inv-metric strong').textContent,money(135000));
assert.equal(leaves[1].querySelector('.inv-secondary strong').textContent,money(90000));
const normal=root.querySelector('.no-variants').querySelector('summary');
assert.equal(normal.querySelector('img').attrs.src,single.photo);
assert.equal(normal.querySelector('[data-card-sale] strong').textContent,money(25000));
assert.equal(normal.querySelector('[data-card-buy] strong').textContent,money(15000));
assert(normal.querySelector('[data-add-product-variant]'));
summary=render({query:'Durpas B'}).querySelector('summary');
assert.match(summary.textContent,/1 dari 2 varian/,'A filter must not detach real groups');
assert(!summary.querySelector('[data-add-product-variant]'));
assert.equal(summary.querySelector('img').attrs.src,b.photo);
assert.equal(summary.querySelector('[data-card-sale] strong').textContent,money(135000));
assert.equal(render({sort:'price-high'}).querySelector('.has-variants summary img').attrs.src,b.photo);
assert.deepEqual(state,before,'Rendering cannot mutate product metadata or stocks');

b.buyPrice=null;b.salePrice=null;
summary=render().querySelector('.has-variants summary');
assert.equal(summary.querySelector('[data-card-buy] strong').textContent,money(30000));
assert.match(summary.querySelector('[data-card-buy]').textContent,/1 harga belum diisi/);
b.buyPrice=0;b.salePrice=50000;
summary=render().querySelector('.has-variants summary');
assert.equal(summary.querySelector('[data-card-sale] strong').textContent,money(50000),'Equal prices show one fixed value');
assert.equal(summary.querySelector('[data-card-buy] strong').textContent,`${money(0)} – ${money(30000)}`,'A real zero buy price remains valid');
a.photo='';summary=render().querySelector('.has-variants summary');
assert(!summary.querySelector('img'),'A missing first photo uses the placeholder, never an unrelated variant photo');
Object.assign(a,{itemType:'direct',stockUnit:'kg_butir',category:'Buah',priceKg:70000,pricePiece:140000});
Object.assign(b,{itemType:'direct',stockUnit:'kg_butir',category:'Buah',priceKg:90000,pricePiece:180000});
summary=render().querySelector('.has-variants summary');
assert.equal(summary.querySelector('[data-card-sale] strong').textContent,`${money(70000)} – ${money(90000)}`);
assert.match(summary.querySelector('[data-card-sale]').textContent,/KG/);
assert(summary.querySelector('[data-card-sale]').textContent.includes(`${money(140000)} – ${money(180000)} / butir`));

// Deleting a sibling must preserve the survivor, including used stock/history.
state.lots=[{id:'lot',productId:a.id,storeId:'outlet',kg:9,pieces:3}];
const survivor=structuredClone(a),stock=structuredClone(state.lots);
assert.throws(()=>deleteProduct(state,{id:b.id}),/Konfirmasi/);
assert.throws(()=>deleteProduct(state,{id:a.id,confirmed:true}),/sudah digunakan/);
assert.equal(state.products.length,3);
deleteProduct(state,{id:b.id,confirmed:true});
assert.deepEqual(a,{...survivor,variantGroupId:null,variantGroupName:null,variantOptions:[],variant:''});
assert.deepEqual(state.lots,stock);
assert(!render().querySelector('.has-variants'));
assert(!render().textContent.includes('1 varian'));
assert.equal(posMenuEntries(state).find(entry=>entry.products[0].id===a.id).hasVariants,false,'Cashier must no longer ask for a single variant');
deleteProduct(state,{id:b.id,confirmed:true});assert.equal(state.products.length,2,'A repeated delete is harmless');

const old=product('old','Durian Bawor',{variantGroupId:'old-group',variantGroupName:'Durian Bawor',variantOptions:[{name:'Varian',value:'Original'}]});
state.products.push(old);
assert(!render().textContent.includes('1 varian'),'Legacy singleton should render as a normal product');
collapseSingleVariants(state.products);assert.equal(old.variantGroupId,null);
collapseSingleVariants(state.products);assert.equal(old.variantOptions.length,0);
console.log('PASS product cards: thumbnails, sorting/filtering, fixed/range prices, missing/zero prices, kg/butir separation, standalone products, deletion guards, preserved stock/identity and singleton POS behavior.');
