-- Update 016: username, foto profil, login identifier, dan reset password owner.
begin;
alter table public.md_pos_employees add column if not exists username text;
alter table public.md_pos_employees add column if not exists profile_photo text;
create unique index if not exists md_pos_employees_username_lower on public.md_pos_employees(lower(username)) where username is not null and username<>'';
do $$begin if not exists(select 1 from pg_constraint where conname='md_pos_employees_username_format') then alter table public.md_pos_employees add constraint md_pos_employees_username_format check(username is null or username ~ '^[A-Za-z0-9._-]{3,40}$');end if;end$$;
do $$begin
 if to_regprocedure('public.pos_mutate_v16(text,jsonb)') is null then alter function public.pos_mutate(text,jsonb) rename to pos_mutate_v16; end if;
 if to_regprocedure('public.pos_read_v16()') is null then alter function public.pos_read() rename to pos_read_v16; end if;
end$$;
create or replace function public.pos_read() returns jsonb language plpgsql security definer set search_path='' as $$declare s jsonb;begin s:=public.pos_read_v16();s:=jsonb_set(s,'{employeeVersion}',to_jsonb(16));s:=jsonb_set(s,'{employees}',coalesce((select jsonb_agg(x||jsonb_build_object('username',e.username,'profile_photo',e.profile_photo)) from jsonb_array_elements(s->'employees') x join public.md_pos_employees e on e.id=(x->>'id')::uuid),'[]'));return s;end$$;
create or replace function public.pos_login_identity(identifier text) returns jsonb language plpgsql security definer set search_path='' as $$declare e public.md_pos_employees%rowtype;v text:=lower(btrim(identifier));begin select * into e from public.md_pos_employees where active and (lower(username)=v or lower(email)=v or regexp_replace(phone,'[^0-9]','','g')=regexp_replace(identifier,'[^0-9]','','g')) limit 1;if not found or e.email='' then raise exception 'Username atau nomor telepon tidak ditemukan';end if;return jsonb_build_object('email',e.email);end$$;
create or replace function public.pos_mutate(action text,payload jsonb) returns jsonb language plpgsql security definer set search_path='' as $$declare me public.md_pos_employees%rowtype;target uuid;safe jsonb;result jsonb;u text;photo text;begin
 if action='employee_save' then perform public.pos_require('employees');select * into me from public.md_pos_employees where user_id=auth.uid() and active;target:=(payload->>'employeeId')::uuid;u:=nullif(lower(btrim(payload->>'username')),'');if u is not null and u !~ '^[a-z0-9._-]{3,40}$' then raise exception 'Username 3-40 karakter: huruf, angka, titik, garis bawah, atau strip';end if;if u is not null and exists(select 1 from public.md_pos_employees where lower(username)=u and id<>target) then raise exception 'Username sudah digunakan';end if;photo:=payload->>'profilePhoto';if photo is not null and length(photo)>2000000 then raise exception 'Foto profil terlalu besar';end if;safe:=payload-'username'-'profilePhoto';result:=public.pos_mutate_v16(action,safe);update public.md_pos_employees set username=u,profile_photo=case when payload ? 'profilePhoto' then nullif(photo,'') else profile_photo end where id=target;return public.pos_read();end if;return public.pos_mutate_v16(action,payload);end$$;
revoke all on function public.pos_read(),public.pos_mutate(text,jsonb),public.pos_login_identity(text) from public,anon,authenticated;grant execute on function public.pos_read(),public.pos_mutate(text,jsonb),public.pos_login_identity(text) to authenticated;
notify pgrst,'reload schema';commit;
