import {categories,itemTypes,stockUnits,productDefaults,isMaterial,isLegacyStock,normalizeProduct} from './catalog.mjs?v=4';
import {escape as e,money,id} from './core.mjs?v=4';
const choice=(values,selected)=>Object.entries(values).map(([key,label])=>`<option value="${e(key)}" ${key===selected?'selected':''}>${e(label)}</option>`).join('');
const label=(text,input)=>`<div class="field"><label>${text}${input}</label></div>`;
export function catalogPanel(products,filter={},state={},store=''){
 const qty=value=>new Intl.NumberFormat('id-ID',{maximumFractionDigits:6}).format(value);
 const stock=p=>{if(!store)return '—';const lots=(isLegacyStock(p)?state.lots:state.unitLots)||[];const own=lots.filter(l=>l.productId===p.id&&l.storeId===store);return isLegacyStock(p)?`${qty(own.reduce((n,l)=>n+l.kg,0))} kg<br>${qty(own.reduce((n,l)=>n+l.pieces,0))} butir`:qty(own.reduce((n,l)=>n+l.qty,0));};
 const rows=products.map(productDefaults).filter(p=>(!filter.category||p.category===filter.category)&&(!filter.itemType||p.itemType===filter.itemType)&&(!filter.query||`${p.name} ${p.sku} ${p.variant||''} ${p.barcode||''}`.toLowerCase().includes(filter.query.toLowerCase())));
 return `<section class="panel"><div class="header-row"><h3>Produk & bahan</h3><button class="primary small" id="add-catalog-product">Tambah item</button></div>
 <form id="catalog-filter" class="filters">${label('Cari nama / SKU',`<input name="query" value="${e(filter.query||'')}" placeholder="Cari produk atau bahan">`)}${label('Kategori jual',`<select name="category"><option value="">Semua kategori</option>${choice(Object.fromEntries(categories.map(x=>[x,x])),filter.category)}</select>`)}${label('Jenis item',`<select name="itemType"><option value="">Semua jenis</option>${choice(itemTypes,filter.itemType)}</select>`)}<button>Terapkan</button></form>
 <p class="muted">Qty Stok: stok fisik tercatat di ${e((state.stores||[]).find(x=>x.id===store)?.name||'store yang dipilih')}, termasuk batch kedaluwarsa. Harga jual mengikuti master produk dan berlaku sama di semua store.</p>
 <div class="table-wrap"><table class="catalog-table"><thead><tr><th>Foto</th><th>Nama Produk</th><th>Variant</th><th>SKU</th><th>Barcode</th><th>Qty Stok</th><th>Satuan</th><th>Harga Beli</th><th>Harga Jual di Toko</th><th>Action</th></tr></thead><tbody>${rows.map(p=>`<tr><td>${p.photo?`<img class="catalog-photo" src="${e(p.photo)}" alt="${e(p.name)}" loading="lazy">`:'<span class="catalog-photo" aria-label="Foto belum tersedia">—</span>'}</td><td><b>${e(p.name)}</b><small class="catalog-meta">${e(p.category||'Bahan')} · ${e(itemTypes[p.itemType])}</small></td><td>${e(p.variant||'—')}</td><td>${e(p.sku)}</td><td>${e(p.barcode||'—')}</td><td class="catalog-stock">${stock(p)}</td><td>${e(stockUnits[p.stockUnit])}</td><td>${p.buyPrice==null?'—':money(p.buyPrice)}${p.buyPrice==null?'':isLegacyStock(p)?' / kg':' / '+e(stockUnits[p.stockUnit])}</td><td>${isMaterial(p)?'Tidak dijual':isLegacyStock(p)?`${money(p.priceKg)} / kg<br>${money(p.pricePiece)} / butir`:`${money(p.salePrice)} / ${e(stockUnits[p.stockUnit])}`}</td><td><button class="small" data-edit-product="${e(p.id)}" aria-label="Edit ${e(p.name)}">Edit</button></td></tr>`).join('')||'<tr><td colspan="10" class="empty">Tidak ada item yang sesuai.</td></tr>'}</tbody></table></div><p class="muted catalog-note">Harga beli adalah harga referensi per satuan, belum perhitungan HPP. Variant adalah keterangan setiap SKU. Penjualan hasil produksi melalui kasir menyusul.</p></section>`;
}
export {productDialog} from './product-dialog.mjs?v=4';
