import {escape as e,num,today,id} from './core.mjs?v=5';
import {scalar,inputTypes,outputTypes,unitLabel,recipeValues,productionPreview,stockQty} from './production.mjs?v=5';
const field=(label,body)=>`<label class="field">${label}${body}</label>`;
const opts=(items,selected)=>items.map(p=>`<option value="${e(p.id)}" ${p.id===selected?'selected':''}>${e(p.name)}</option>`).join('');
const item=(s,key)=>s.products.find(p=>p.id===key);
function setQuantityUnit(input,unit){const whole=['pcs','porsi'].includes(unit);input.min=whole?'1':'0.000001';input.step=whole?'1':'any';}
const ingredientsText=lines=>lines.map(l=>`${e(l.name)}: ${num(l.qty)} ${e(unitLabel[l.unit]||l.unit)}`).join('<br>');
export function recipesPage(s){return`<div class="intro"><div><h2>Master Resep</h2><p class="muted">Takaran untuk satu kali resep. Bahan dipotong saat Create Product disimpan.</p></div><button class="primary" id="new-recipe">Tambah resep</button></div><section class="panel"><div class="table-wrap"><table><thead><tr><th>RESEP</th><th>HASIL PER RESEP</th><th>BAHAN</th><th>AKSI</th></tr></thead><tbody>${(s.recipes||[]).map(r=>`<tr><td><b>${e(r.name)}</b><small>Versi ${r.version}</small></td><td>${e(item(s,r.outputId)?.name)}<br>${num(r.yieldQty)} ${e(unitLabel[item(s,r.outputId)?.stockUnit])}</td><td>${ingredientsText(r.ingredients.map(l=>({...l,name:item(s,l.productId)?.name,unit:item(s,l.productId)?.stockUnit})))}</td><td><button class="small" data-edit-recipe="${e(r.id)}">Edit</button></td></tr>`).join('')||'<tr><td colspan="4" class="empty">Daftarkan bahan dan hasil di Master data, lalu buat resep pertama.</td></tr>'}</tbody></table></div></section>`;}
export function productionPage(s,store){return`<div class="intro"><div><h2>Create Product</h2><p class="muted">Produksi bahan siap pakai atau menu harian di store aktif.</p></div><button id="refresh-production">Perbarui stok</button></div><section class="panel"><form id="production-form"><div class="form-grid">${field('Resep',`<select name="recipeId" required><option value="">Pilih resep</option>${opts(s.recipes||[])}</select>`)}${field('Tanggal produksi',`<input name="date" type="date" value="${today()}" required>`)}${field('Berapa kali resep dibuat?', '<input name="batches" type="number" min="1" max="10000" step="1" value="1" required>')}${field('Hasil aktual (sesuai satuan resep)','<input name="actualQty" type="number" min="0.000001" step="any" required>')}${field('Kedaluwarsa hasil (opsional)','<input name="expiry" type="date">')}${field('Catatan','<input name="note" maxlength="300" placeholder="Contoh: produksi pagi">')}</div><div id="production-preview" aria-live="polite"><p class="muted">Pilih resep untuk melihat kebutuhan bahan.</p></div><p class="error" id="production-error"></p><button type="submit" class="primary" ${store?'':'disabled'}>Simpan produksi & potong bahan</button></form></section>${unitStockPanel(s,store)}<section class="panel"><h3>Riwayat produksi store ini</h3><div class="table-wrap"><table><thead><tr><th>TANGGAL / RESEP</th><th>HASIL</th><th>BAHAN TERPAKAI</th><th>STATUS</th></tr></thead><tbody>${(s.productions||[]).filter(r=>r.storeId===store).slice().reverse().map(r=>`<tr><td>${e(r.date)}<br><b>${e(r.recipeName)}</b><small>${e(r.id.slice(0,8))} · v${r.recipeVersion} · ${num(r.batches)} kali resep</small></td><td>${e(r.outputName)}<br><b>${num(r.actualQty)} ${e(unitLabel[r.unit])}</b><small>Target ${num(r.expectedQty)}</small></td><td>${ingredientsText(r.ingredients)}</td><td>${r.voided?`Dibatalkan<br><small>${e(r.voidReason)}</small>`:`<button class="small danger" data-void-production="${e(r.id)}">Batalkan</button>`}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">Belum ada produksi.</td></tr>'}</tbody></table></div></section>`;}
export function unitStockPanel(s,store){const lots=(s.unitLots||[]).filter(l=>l.storeId===store);return`<section class="panel"><div class="header-row"><h3>Stok bahan & hasil produksi</h3><button id="unit-receipt" class="small primary">Stok bahan / stok awal</button></div><p class="muted">Stok siap dipakai produksi. Penjualan stok hasil produksi melalui kasir akan dihubungkan pada tahap berikutnya.</p><div class="table-wrap"><table><thead><tr><th>ITEM</th><th>STOK FISIK TERCATAT</th><th>LAYAK PAKAI HARI INI</th></tr></thead><tbody>${s.products.filter(scalar).map(p=>`<tr><td>${e(p.name)}</td><td>${num(lots.filter(l=>l.productId===p.id).reduce((a,l)=>a+l.qty,0))} ${e(unitLabel[p.stockUnit])}</td><td>${num(stockQty(s,p.id,store,today()))} ${e(unitLabel[p.stockUnit])}</td></tr>`).join('')||'<tr><td colspan="3" class="empty">Daftarkan bahan dan hasil produksi di Master data.</td></tr>'}</tbody></table></div><details><summary>Rincian penerimaan dan batch hasil</summary><div class="table-wrap"><table><thead><tr><th>TANGGAL / BATCH</th><th>ITEM / ASAL</th><th>AWAL → SISA</th><th>KEDALUWARSA / CATATAN</th></tr></thead><tbody>${lots.slice().reverse().map(l=>`<tr><td>${e(l.date)}<br><small>${e(l.id.slice(0,8))}</small></td><td>${e(item(s,l.productId)?.name)}<br><small>${e(({opening:'Stok awal',purchase:'Pembelian',production:'Hasil produksi',waste:'Hasil waste / olahan'})[l.kind])}${l.supplierId?' · '+e(s.suppliers.find(x=>x.id===l.supplierId)?.name):''}</small></td><td>${num(l.receivedQty)} → ${num(l.qty)} ${e(unitLabel[l.unit])}</td><td>${e(l.expiry||'—')}<br><small>${e(l.note)}</small></td></tr>`).join('')}</tbody></table></div></details></section>`;}
export function recipeDialog(s,ctx,existing){
 const outputs=s.products.filter(p=>scalar(p)&&outputTypes.includes(p.itemType)),inputs=s.products.filter(p=>scalar(p)&&inputTypes.includes(p.itemType));
 if(!outputs.length||!inputs.length)return ctx.toast('Daftarkan bahan dan item hasil produksi di Master data terlebih dahulu');
 const r=existing||{id:id(),name:'',outputId:outputs[0].id,yieldQty:1,version:0,ingredients:[{productId:inputs[0].id,qty:1}]};
 const d=ctx.modal(existing?'Edit resep':'Tambah resep',`${field('Nama resep',`<input name="name" value="${e(r.name)}" required maxlength="100">`)}${field('Item hasil produksi',`<select name="outputId">${opts(outputs,r.outputId)}</select>`)}${field('Jumlah hasil untuk satu kali resep',`<input name="yieldQty" type="number" min="0.000001" step="any" value="${r.yieldQty}" required>`)}<p class="muted" id="yield-unit"></p><div id="recipe-lines"></div><button type="button" id="add-ingredient">Tambah bahan</button><p class="muted">Gunakan satuan master bahan. Contoh: 1 kg tepung diisi 1000 gram. Resep cendol mengonsumsi tepung; resep dessert mengonsumsi stok cendol yang sudah jadi.</p>`);
 const f=d.querySelector('form'),control=n=>f.elements.namedItem(n);let rows=r.ingredients.map(x=>({...x}));
 const capture=()=>{rows=[...d.querySelectorAll('[data-ingredient-row]')].map(row=>({productId:row.querySelector('select').value,qty:row.querySelector('input').value}));};
 function draw(){d.querySelector('#recipe-lines').innerHTML=rows.map((l,i)=>`<div class="recipe-line" data-ingredient-row>${field('Bahan',`<select>${opts(inputs,l.productId)}</select>`)}${field('Jumlah ('+e(unitLabel[item(s,l.productId)?.stockUnit])+')',`<input type="number" min="0.000001" step="any" value="${e(l.qty)}" required>`)}<button type="button" data-remove-ingredient="${i}" aria-label="Hapus bahan ${i+1}">×</button></div>`).join('');d.querySelectorAll('[data-remove-ingredient]').forEach(b=>b.onclick=()=>{capture();rows.splice(Number(b.dataset.removeIngredient),1);draw();});d.querySelectorAll('[data-ingredient-row] select').forEach(el=>el.onchange=()=>{capture();draw();});}
 d.querySelector('#add-ingredient').onclick=()=>{capture();if(rows.length>=50)return ctx.toast('Maksimal 50 bahan');rows.push({productId:inputs[0].id,qty:1});draw();};
 const outputChanged=()=>{const p=item(s,control('outputId').value);d.querySelector('#yield-unit').textContent='Satuan hasil: '+unitLabel[p.stockUnit];setQuantityUnit(control('yieldQty'),p.stockUnit);};control('outputId').onchange=outputChanged;outputChanged();draw();
 f.onsubmit=async ev=>{ev.preventDefault();capture();try{const values=recipeValues(s,{...Object.fromEntries(new FormData(f)),ingredients:rows});if(await ctx.mutate('recipe_save',{id:r.id,version:r.version,...values})){d.close();ctx.render();ctx.toast('Resep tersimpan');}}catch(err){d.querySelector('#form-error').textContent=err.message;}};
}
export function receiptDialog(s,store,ctx){
 const products=s.products.filter(scalar);if(!store||!products.length)return ctx.toast('Pilih store dan daftarkan item terlebih dahulu');
 const requestId=id();const d=ctx.modal('Stok bahan / stok awal',`${field('Jenis penerimaan','<select name="kind"><option value="purchase">Pembelian</option><option value="opening">Stok awal yang sudah tersedia</option></select>')}${field('Item','<select name="productId" required></select>')}<p class="muted" id="receipt-unit"></p>${field('Jumlah','<input name="qty" type="number" min="0.000001" step="any" required>')}${field('Tanggal masuk',`<input name="date" type="date" value="${today()}" required>`)}<div id="supplier-field">${field('Supplier',`<select name="supplierId"><option value="">Pilih supplier</option>${opts(s.suppliers)}</select>`)}</div>${field('Kedaluwarsa (opsional)','<input name="expiry" type="date">')}${field('Catatan','<input name="note" maxlength="300" placeholder="Wajib untuk stok awal">')}`);
 const f=d.querySelector('form'),c=n=>f.elements.namedItem(n);
 const unit=()=>{const p=item(s,c('productId').value);d.querySelector('#receipt-unit').textContent=p?'Satuan: '+unitLabel[p.stockUnit]:'Belum ada item untuk jenis penerimaan ini';setQuantityUnit(c('qty'),p?.stockUnit);};
 const refresh=()=>{const purchase=c('kind').value==='purchase';c('productId').innerHTML=opts(products.filter(p=>!purchase||['raw','direct'].includes(p.itemType)));c('supplierId').required=purchase;c('supplierId').disabled=!purchase;d.querySelector('#supplier-field').hidden=!purchase;c('note').required=!purchase;unit();};c('kind').onchange=refresh;c('productId').onchange=unit;refresh();
 f.onsubmit=async ev=>{ev.preventDefault();if(await ctx.mutate('unit_receipt',{...Object.fromEntries(new FormData(f)),id:requestId,storeId:store})){d.close();ctx.render();ctx.toast('Stok tersimpan');}};
}
export function bindProduction(view,s,store,ctx){
 document.querySelector('#unit-receipt')?.addEventListener('click',()=>receiptDialog(s,store,ctx));
 if(view==='recipes'){document.querySelector('#new-recipe').onclick=()=>recipeDialog(s,ctx);document.querySelectorAll('[data-edit-recipe]').forEach(b=>b.onclick=()=>recipeDialog(s,ctx,s.recipes.find(r=>r.id===b.dataset.editRecipe)));}
 if(view!=='production')return;
 document.querySelector('#refresh-production').onclick=async()=>{try{await ctx.refresh();ctx.render();}catch(err){ctx.toast(err.message);}};
 const f=document.querySelector('#production-form'),c=n=>f.elements.namedItem(n),requestId=id();
 function preview(resetActual=false){try{
  const recipe=(s.recipes||[]).find(r=>r.id===c('recipeId').value);if(!recipe)throw Error('Pilih resep terlebih dahulu');
  const plan=productionPreview(s,recipe,store,c('batches').value,c('date').value);
  if(resetActual)c('actualQty').value=plan.expectedQty;setQuantityUnit(c('actualQty'),plan.outputUnit);
  document.querySelector('#production-preview').innerHTML=`<div class="callout">Hasil standar: <b>${num(plan.expectedQty)} ${e(unitLabel[plan.outputUnit])} ${e(plan.outputName)}</b>. Isi hasil aktual sesuai produksi nyata; kebutuhan bahan mengikuti jumlah resep.</div><div class="table-wrap"><table><thead><tr><th>BAHAN</th><th>DIBUTUHKAN</th><th>TERSEDIA PADA TANGGAL PRODUKSI</th></tr></thead><tbody>${plan.ingredients.map(l=>`<tr><td>${e(l.name)}</td><td>${num(l.qty)} ${e(unitLabel[l.unit])}</td><td class="${l.available<l.qty?'error':''}">${num(l.available)} ${e(unitLabel[l.unit])}${l.available<l.qty?' · Kurang':''}</td></tr>`).join('')}</tbody></table></div>`;
  document.querySelector('#production-error').textContent=plan.ingredients.some(l=>l.available<l.qty)?'Stok bahan belum cukup. Lengkapi stok sebelum produksi.':'';return{recipe,plan};
 }catch(err){document.querySelector('#production-error').textContent=err.message;return null;}}
 c('recipeId').onchange=()=>preview(true);c('batches').oninput=()=>preview(true);c('date').onchange=()=>preview(false);
 f.onsubmit=async ev=>{ev.preventDefault();const result=preview();if(!result)return;const {recipe,plan}=result;if(plan.ingredients.some(l=>l.available<l.qty))return;
  if(await ctx.mutate('produce',{...Object.fromEntries(new FormData(f)),id:requestId,storeId:store,recipeVersion:recipe.version})){ctx.render();ctx.toast('Produksi tersimpan: bahan berkurang dan hasil masuk stok');}
 };
 document.querySelectorAll('[data-void-production]').forEach(b=>b.onclick=()=>{const d=ctx.modal('Batalkan pencatatan produksi',`${field('Alasan','<input name="reason" required maxlength="300">')}<p class="muted">Hanya untuk salah pencatatan dan hasil yang belum digunakan. Seluruh bahan dikembalikan ke batch asal.</p>`,'Batalkan produksi');d.querySelector('form').onsubmit=async ev=>{ev.preventDefault();if(await ctx.mutate('production_void',{id:id(),productionId:b.dataset.voidProduction,reason:new FormData(ev.currentTarget).get('reason')})){d.close();ctx.render();ctx.toast('Produksi dibatalkan; bahan dikembalikan');}};});
}
