// Generated by npm run pwa:build. Only public app assets enter Cache Storage.
const CACHE='maniac-pos-shell-0199c10c317f167c';
const ASSETS=["/pos/amounts.mjs","/pos/app.js","/pos/batch-tracking.mjs","/pos/batch-ui.mjs","/pos/catalog-table.css","/pos/catalog-ui.mjs","/pos/catalog.mjs","/pos/core.mjs","/pos/employees-ui.mjs","/pos/employees.css","/pos/finance.mjs","/pos/index.html","/pos/inventory-ui.mjs","/pos/inventory.css","/pos/logo.png","/pos/manifest.webmanifest","/pos/money-input.mjs","/pos/navigation.mjs","/pos/offline.mjs","/pos/operations-ui.mjs","/pos/order-stock.mjs","/pos/pos.css","/pos/product-details.mjs","/pos/product-dialog.mjs","/pos/product-stock.mjs","/pos/production-ui.mjs","/pos/production.mjs","/pos/pwa.mjs","/pos/receipt-weighing.mjs","/pos/retry.mjs","/pos/waste-evidence.mjs","/pos/waste-ui.mjs","/pos/waste.mjs","/shared/photo.mjs","/pos/icons/icon-192.png","/pos/icons/icon-512.png"];
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS))));
// No skipWaiting: open terminals keep a consistent application version.
self.addEventListener('activate',event=>event.waitUntil((async()=>{
 for(const key of await caches.keys())if(key.startsWith('maniac-pos-shell-')&&key!==CACHE)await caches.delete(key);
 await self.clients.claim();
})()));
self.addEventListener('fetch',event=>{
 const url=new URL(event.request.url);
 if(event.request.method!=='GET'||url.origin!==self.location.origin)return;
 let key=url.pathname;
 if(['/pos','/pos/','/pos/index.html'].includes(key))key='/pos/index.html';
 if(!ASSETS.includes(key))return;
 event.respondWith(caches.open(CACHE).then(async cache=>(await cache.match(key))||fetch(event.request)));
});
