// Generated by npm run pwa:build. Public assets only; never API or transaction data.
const CACHE='maniac-pos-shell-adaf8f5c45b28b76';
const ASSETS=["/pos/amounts.mjs","/pos/app.js","/pos/batch-tracking.mjs","/pos/batch-ui.mjs","/pos/catalog-table.css","/pos/catalog-ui.mjs","/pos/catalog.mjs","/pos/core.mjs","/pos/employees-ui.mjs","/pos/employees.css","/pos/finance.mjs","/pos/index.html","/pos/inventory-ui.mjs","/pos/inventory.css","/pos/logo.png","/pos/manifest.webmanifest","/pos/money-input.mjs","/pos/navigation.mjs","/pos/offline.mjs","/pos/operations-ui.mjs","/pos/order-stock.mjs","/pos/pos.css","/pos/product-details.mjs","/pos/product-dialog.mjs","/pos/product-stock.mjs","/pos/production-ui.mjs","/pos/production.mjs","/pos/pwa.mjs","/pos/receipt-weighing.mjs","/pos/retry.mjs","/pos/waste-evidence.mjs","/pos/waste-ui.mjs","/pos/waste.mjs","/shared/photo.mjs","/pos/icons/icon-192.png","/pos/icons/icon-512.png"];
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS))));
// Keep existing terminals stable until all clients release the previous worker.
self.addEventListener('activate',event=>event.waitUntil((async()=>{
 for(const key of await caches.keys())if(key.startsWith('maniac-pos-shell-')&&key!==CACHE)await caches.delete(key);
 await self.clients.claim();
})()));
self.addEventListener('fetch',event=>{
 const url=new URL(event.request.url);
 if(event.request.method!=='GET'||url.origin!==self.location.origin)return;
 const pathname=['/pos','/pos/','/pos/index.html'].includes(url.pathname)?'/pos/index.html':url.pathname;
 if(!ASSETS.includes(pathname))return;
 // Match the complete request, including ?v=. Never substitute a different version.
 event.respondWith((async()=>{
  const cache=await caches.open(CACHE).catch(()=>null);
  try{
   const response=await fetch(event.request,{cache:'no-cache'});
   if(response.ok&&cache)await cache.put(event.request,response.clone()).catch(()=>{});
   return response;
  }catch(error){
   const cached=await cache?.match(event.request);
   if(cached)return cached;
   if(!url.search&&cache){const unversioned=await cache.match(pathname);if(unversioned)return unversioned;}
   throw error;
  }
 })());
});
