import fs from 'node:fs';
import {createHash} from 'node:crypto';
const files=fs.readdirSync('pos').filter(f=>/\.(m?js|css|html|webmanifest|png)$/.test(f)&&f!=='sw.js').map(f=>'/pos/'+f);
files.push('/shared/photo.mjs','/pos/icons/icon-192.png','/pos/icons/icon-512.png');
const hash=createHash('sha256');for(const f of files)hash.update(f).update(fs.readFileSync('.'+f));
const version=hash.digest('hex').slice(0,16);
fs.writeFileSync('pos/sw.js',`// Generated by npm run pwa:build. Only public app assets enter Cache Storage.\nconst CACHE='maniac-pos-shell-${version}';\nconst ASSETS=${JSON.stringify(files)};\nself.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS))));\n// No skipWaiting: open terminals keep a consistent application version.\nself.addEventListener('activate',event=>event.waitUntil((async()=>{\n for(const key of await caches.keys())if(key.startsWith('maniac-pos-shell-')&&key!==CACHE)await caches.delete(key);\n await self.clients.claim();\n})()));\nself.addEventListener('fetch',event=>{\n const url=new URL(event.request.url);\n if(event.request.method!=='GET'||url.origin!==self.location.origin)return;\n let key=url.pathname;\n if(['/pos','/pos/','/pos/index.html'].includes(key))key='/pos/index.html';\n if(!ASSETS.includes(key))return;\n event.respondWith(caches.open(CACHE).then(async cache=>(await cache.match(key))||fetch(event.request)));\n});\n`);
console.log('Generated POS service worker '+version+' ('+files.length+' app assets).');
