import fs from 'node:fs';
import {createHash} from 'node:crypto';
const files=fs.readdirSync('pos').filter(f=>/\.(m?js|css|html|webmanifest|png)$/.test(f)&&f!=='sw.js').map(f=>'/pos/'+f);
files.push('/shared/photo.mjs','/pos/icons/icon-192.png','/pos/icons/icon-512.png');
const hash=createHash('sha256');for(const f of files)hash.update(f).update(fs.readFileSync('.'+f));
const version=hash.digest('hex').slice(0,16);
fs.writeFileSync('pos/sw.js',`// Generated by npm run pwa:build. Public assets only; never API or transaction data.
const CACHE='maniac-pos-shell-${version}';
const ASSETS=${JSON.stringify(files)};
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS))));
// Keep existing terminals stable until all clients release the previous worker.
self.addEventListener('activate',event=>event.waitUntil((async()=>{
 for(const key of await caches.keys())if(key.startsWith('maniac-pos-shell-')&&key!==CACHE)await caches.delete(key);
 await self.clients.claim();
})()));
self.addEventListener('fetch',event=>{
 const url=new URL(event.request.url);
 if(event.request.method!=='GET'||url.origin!==self.location.origin)return;
 const pathname=['/pos','/pos/','/pos/index.html'].includes(url.pathname)?'/pos/index.html':url.pathname;
 if(!ASSETS.includes(pathname))return;
 // Match the complete request, including ?v=. Never substitute a different version.
 event.respondWith((async()=>{
  const cache=await caches.open(CACHE).catch(()=>null);
  try{
   const response=await fetch(event.request,{cache:'no-cache'});
   if(response.ok&&cache)await cache.put(event.request,response.clone()).catch(()=>{});
   return response;
  }catch(error){
   const cached=await cache?.match(event.request);
   if(cached)return cached;
   if(!url.search&&cache){const unversioned=await cache.match(pathname);if(unversioned)return unversioned;}
   throw error;
  }
 })());
});
`);
console.log('Generated version-aware POS service worker '+version);
